package com.wislie.wanandroid.util

const val ARTICLE_ID = "articleId"
const val ARTICLE_ORIGIN_ID = "originId"
const val ARTICLE_TITLE = "title"
const val ARTICLE_LINK = "link"
const val ARTICLE_AUTHOR = "author"
const val ARTICLE_COLLECT = "collect"
const val ARTICLE_TYPE = "type"
const val ACCOUNT_ID = "accountId"
const val TODO_ID = "todoId"
const val TODO_TITLE = "title"
const val TODO_CONTENT = "content"
const val TODO_DATE = "dateStr"
const val TODO_STATUS = "status"
const val TODO_TYPE = "type"
const val TODO_PRIORITY = "priority"
const val TREE_ID = "treeId"
const val TREE_INFO = "info"
const val TREE_TITLE = "title"