{
  "formatVersion": "1.1",
  "component": {
    "group": "WanAndroid-Koltin",
    "module": "asm_nodouble_click",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "Maven-0.0.1.jar",
          "url": "Maven-0.0.1.jar",
          "size": 16637,
          "sha512": "9b7a76e99c4669e6719eceb9bd95c5519a5bd545e019e4914fbd46ccb8bb2036e4f9863a0a1c4573c3e6b35eabe4a3d4b4c9a087d4a5f3567145370b1a14711d",
          "sha256": "8803c6db53288bf0866ff603e6de41ae1134890b98fa51fc1b9a689f309663a7",
          "sha1": "c4b9b06adb3e035d058ea7fb0453590a90f49ba4",
          "md5": "fe2a3a4d0fadbdf892933588e2781658"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "Maven-0.0.1.jar",
          "url": "Maven-0.0.1.jar",
          "size": 16637,
          "sha512": "9b7a76e99c4669e6719eceb9bd95c5519a5bd545e019e4914fbd46ccb8bb2036e4f9863a0a1c4573c3e6b35eabe4a3d4b4c9a087d4a5f3567145370b1a14711d",
          "sha256": "8803c6db53288bf0866ff603e6de41ae1134890b98fa51fc1b9a689f309663a7",
          "sha1": "c4b9b06adb3e035d058ea7fb0453590a90f49ba4",
          "md5": "fe2a3a4d0fadbdf892933588e2781658"
        }
      ]
    }
  ]
}
