{
  "formatVersion": "1.1",
  "component": {
    "group": "WanAndroid-Koltin",
    "module": "asm_nodouble_click",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "Maven-0.0.1.jar",
          "url": "Maven-0.0.1.jar",
          "size": 16639,
          "sha512": "494ec318a3952f06f0755cde1c626034d912c966bc154b6e820b1ec746f7c6e9bbd4c7d17a37128a7bd3f29ee281c63d0a3908a532ca9f28a030455c7e789127",
          "sha256": "faac5fd42a49ccdc65d953beb4b75e1b3a1a329f0b5d6fd7fc61936dfb9bd890",
          "sha1": "030509979d68b9f02519e37c39f1b1692bebc957",
          "md5": "faaf0922dc94880777a71c2f7ab9b1e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "Maven-0.0.1.jar",
          "url": "Maven-0.0.1.jar",
          "size": 16639,
          "sha512": "494ec318a3952f06f0755cde1c626034d912c966bc154b6e820b1ec746f7c6e9bbd4c7d17a37128a7bd3f29ee281c63d0a3908a532ca9f28a030455c7e789127",
          "sha256": "faac5fd42a49ccdc65d953beb4b75e1b3a1a329f0b5d6fd7fc61936dfb9bd890",
          "sha1": "030509979d68b9f02519e37c39f1b1692bebc957",
          "md5": "faaf0922dc94880777a71c2f7ab9b1e8"
        }
      ]
    }
  ]
}
