{
  "formatVersion": "1.1",
  "component": {
    "group": "WanAndroid-Koltin",
    "module": "asm_nodouble_click",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "Maven-0.0.1.jar",
          "url": "Maven-0.0.1.jar",
          "size": 16637,
          "sha512": "0f5119e813724e52a80e599fe9f8854adb80ccabdebe37a95b52b194337639e33a32ace4a86af94a594f5938a8586fd173632af31a8047230baa93ae1e74b668",
          "sha256": "0032d38270b66b321d9336dbb1084f176045b8d8a92157665bfea91362fd276e",
          "sha1": "27c8a1f57b92ec2b88f7f5488e8c0437ec453da5",
          "md5": "9951c856bbb194092b5ace60758a3cb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "Maven-0.0.1.jar",
          "url": "Maven-0.0.1.jar",
          "size": 16637,
          "sha512": "0f5119e813724e52a80e599fe9f8854adb80ccabdebe37a95b52b194337639e33a32ace4a86af94a594f5938a8586fd173632af31a8047230baa93ae1e74b668",
          "sha256": "0032d38270b66b321d9336dbb1084f176045b8d8a92157665bfea91362fd276e",
          "sha1": "27c8a1f57b92ec2b88f7f5488e8c0437ec453da5",
          "md5": "9951c856bbb194092b5ace60758a3cb5"
        }
      ]
    }
  ]
}
